---
# usage:
# 1. install ansible http://docs.ansible.com/ansible/intro_installation.html#getting-ansible
# 2. add your ssh public key id_rsa.pub to /root/.ssh/authorized_keys
# 3. run this command:
#    ansible-playbook provision.yml

- hosts: cal.webmedecin.net
  remote_user: root
  vars:
    user1 : philippe
    user2: jerome  
  tasks:
   - name: Install apt-transport-https
     apt: pkg=apt-transport-https state=installed update_cache=true

   - name: add Docker apt key
     apt_key: id=0x9DC858229FC7DD38854AE2D88D81803C0EBFCD88 keyserver='ha.pool.sks-keyservers.net' keyring='/etc/apt/trusted.gpg.d/docker.gpg' state=present 

   - name: Add Docker repository
     apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/debian stretch stable' state=present filename='docker' update_cache='yes'

   - name: Install Docker CE                                          
     apt: pkg=docker-ce state=installed update_cache=true  

   - name: add user1 to docker group
     user: name={{ user1 }} groups=docker append=yes

   - name: add user2 to docker group                                            
     user: name={{ user2 }} groups=docker append=yes

   - name: Install git                                                    
     apt: pkg=git state=installed update_cache=true

   - name: Install certbot to get Letsencrypt TLS certificates free of charge
     apt: pkg=certbot state=installed update_cache=true

   - name: Install nginx (reverse proxy 80 to 8008)   
     apt: pkg=nginx state=installed update_cache=true 
